def protocol_to_int(protocol_name):
    proto_map = {
        "3pc": 0,
        "a/n": 1,
        "aes-sp3-d": 2,
        "any": 3,
        "argus": 4,
        "aris": 5,
        "arp": 6,
        "ax.25": 7,
        "bbn-rcc": 8,
        "bna": 9,
        "br-sat-mon": 10,
        "cbt": 11,
        "cftp": 12,
        "chaos": 13,
        "compaq-peer": 14,
        "cphb": 15,
        "cpnx": 16,
        "crtp": 17,
        "crudp": 18,
        "dcn": 19,
        "ddp": 20,
        "ddx": 21,
        "dgp": 22,
        "egp": 23,
        "eigrp": 24,
        "emcon": 25,
        "encap": 26,
        "etherip": 27,
        "fc": 28,
        "fire": 29,
        "ggp": 30,
        "gmtp": 31,
        "gre": 32,
        "hmp": 33,
        "i-nlsp": 34,
        "iatp": 35,
        "ib": 36,
        "icmp": 37,
        "idpr": 38,
        "idpr-cmtp": 39,
        "idrp": 40,
        "ifmp": 41,
        "igmp": 42,
        "igp": 43,
        "il": 44,
        "ip": 45,
        "ipcomp": 46,
        "ipcv": 47,
        "ipip": 48,
        "iplt": 49,
        "ipnip": 50,
        "ippc": 51,
        "ipv6": 52,
        "ipv6-frag": 53,
        "ipv6-no": 54,
        "ipv6-opts": 55,
        "ipv6-route": 56,
        "ipx-n-ip": 57,
        "irtp": 58,
        "isis": 59,
        "iso-ip": 60,
        "iso-tp4": 61,
        "kryptolan": 62,
        "l2tp": 63,
        "larp": 64,
        "leaf-1": 65,
        "leaf-2": 66,
        "merit-inp": 67,
        "mfe-nsp": 68,
        "mhrp": 69,
        "micp": 70,
        "mobile": 71,
        "mtp": 72,
        "mux": 73,
        "narp": 74,
        "netblt": 75,
        "nsfnet-igp": 76,
        "nvp": 77,
        "ospf": 78,
        "pgm": 79,
        "pim": 80,
        "pipe": 81,
        "pnni": 82,
        "pri-enc": 83,
        "prm": 84,
        "ptp": 85,
        "pup": 86,
        "pvp": 87,
        "qnx": 88,
        "rdp": 89,
        "rsvp": 90,
        "rtp": 91,
        "rvd": 92,
        "sat-expak": 93,
        "sat-mon": 94,
        "sccopmce": 95,
        "scps": 96,
        "sctp": 97,
        "sdrp": 98,
        "secure-vmtp": 99,
        "sep": 100,
        "skip": 101,
        "sm": 102,
        "smp": 103,
        "snp": 104,
        "sprite-rpc": 105,
        "sps": 106,
        "srp": 107,
        "st2": 108,
        "stp": 109,
        "sun-nd": 110,
        "swipe": 111,
        "tcf": 112,
        "tcp": 113,
        "tlsp": 114,
        "tp++": 115,
        "trunk-1": 116,
        "trunk-2": 117,
        "ttp": 118,
        "udp": 119,
        "unas": 120,
        "uti": 121,
        "vines": 122,
        "visa": 123,
        "vmtp": 124,
        "vrrp": 125,
        "wb-expak": 126,
        "wb-mon": 127,
        "wsn": 128,
        "xnet": 129,
        "xns-idp": 130,
        "xtp": 131,
        "zero": 132,
    }

    proto_value = proto_map.get(protocol_name.lower())
    
    return proto_value

def service_to_int(service_name):
    service_map = {
        "-": 0,
        "dhcp": 1,
        "dns": 2,
        "ftp": 3,
        "ftp-data": 4,
        "http": 5,
        "irc": 6,
        "pop3": 7,
        "radius": 8,
        "smtp": 9,
        "snmp": 10,
        "ssh": 11,
        "ssl": 12
    }

    service_value = service_map.get(service_name.lower())

    return service_value

def state_to_int(state_name):
    state_map = {
        "ACC": 0,
        "CLO": 1,
        "CON": 2,
        "ECO": 3,
        "FIN": 4,
        "INT": 5,
        "PAR": 6,
        "REQ": 7,
        "RST": 8,
        "URN": 9,
        "no": 10
    }

    state_value = state_map.get(state_name)

    return state_value




